---
openapi: 3.0.2
info:
  title: IO Avatar作成API
  version: 1.0.0
  description: IOがAvatarからdeviceTokenを受信し、accountUniqueを発番して、Avatarサーバに仮登録リクエストとPush通知を依頼するAPIです。
  license:
    name: ほげ API利用規約
    url: https://www.hoge.com/ec/sitepolicy/index.html
servers:
- url: https://iofrontend.apps.cnt3-r45-jyvwjf.hoge-xws.com
  description: 開発環境
- url: https://iofrontend.apps.cnt4-r67-jyvwjf.hoge-xws.com
  description: 検証環境（社内）
- url: https://id-staging.hoge.com
  description: 検証環境（インターネット）
  x-environment: ""
  x-upstream: []
paths:
  /io/v1/Account/Create:
    summary: 新規ユーザの作成。
    description: 新規ユーザの作成をする。
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
            examples:
              sample_Create:
                value:
                  deviceToken: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                  platform: android
        required: true
      tags:
      - IO
      responses:
        "201":
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
              examples:
                sample_201:
                  value:
                    type: about:blank
                    detail: 正常実行されました
                    code: S-000
                    resultset: {}
                    results: []
          description: 新規ユーザの作成成功
        "400":
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
              examples:
                sample_400:
                  value:
                    type: about:blank
                    detail: deviceTokenがnullまたは空文字です
                    code: C-101
                    resultset: {}
                    results: []
          description: "新規ユーザの作成失敗 \n\n エラーがユーザに起因する場合に返却"
        "500":
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
              examples:
                sample_500:
                  value:
                    type: about:blank
                    detail: 予期しないエラーが発生しました。
                    code: E-000
                    resultset: {}
                    results: []
          description: "新規ユーザの作成失敗 \n\n エラーがioサーバに起因する場合に返却"
        "503":
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/CreateAccountResponse'
              examples:
                sample_503:
                  value:
                    type: about:blank
                    detail: Avatarサービスとの通信でエラーが発生しました。
                    code: E-201
                    resultset: {}
                    results: []
          description: "新規ユーザの作成失敗 \n\n エラーが外部サービスに起因する場合に返却"
      operationId: createAccount
components:
  schemas:
    CreateAccountRequest:
      description: 新規ユーザ登録のリクエスト
      required:
      - deviceToken
      - platform
      type: object
      properties:
        deviceToken:
          description: デバイストークン
          maxLength: 255
          minLength: 1
          type: string
        platform:
          description: プラットフォーム
          enum:
          - android
          - webpush
          - apns
          - macsafari
          type: string
    CreateAccountResponse:
      description: 新規ユーザ登録のレスポンス
      required:
      - type
      - detail
      - code
      - resultset
      - results
      type: object
      properties:
        type:
          description: API設計書のURI
          type: string
        detail:
          nullable: true
          description: "正常メッセージ/エラーメッセージ  \n\n 本番環境はnullを返却"
          type: string
        code:
          description: "結果コード \n\n 以下いずれかの値を設定 \n\n 正常実行(S-XXX) \n\n - S-000 正常実行　\
            \n - S-001 該当データなし　\n\n ユーザに起因するエラー(C-XXX) \n\n - C-1XX パラメータエラー  \n -\
            \ C-2XX 業務エラー  \n\n システムに起因するエラー(E-XXX) \n\n - E-000 予期しないエラー \n - E-1XX\
            \ 内部システムエラー \n - E-2XX 外部システムエラー \n\n /IO/v1/Account/Create が返却する結果コード\
            \ \n - S-000 正常実行 \n - C-101 nullが許容されない呼出パラメータにnullまたは空文字を指定 \n - C-102\
            \ 呼出パラメータのフォーマットが不正(最小値を下回る、最大値上回る、利用できない文字を指定) \n - E-000 IOサーバで予期しない\
            エラーが発生 \n - E-201 Avatarサービスとの通信でエラーが発生 \n - E-202 Avatarサービスでエラーが発生 \n\
            \ - E-203 RDSでエラーが発生 \n "
          type: string
        resultset:
          description: 結果のメタデータ
          type: object
        results:
          description: 結果
          type: array
          items:
            type: object
